[
    {
        "cve": "CVE-2025-32873",
        "poc_github": true,
        "full_name": "Apollo-R3bot/django-vulnerability-CVE-2025-32873",
        "owner_login": "Apollo-R3bot",
        "owner_id": 148726450,
        "owner_html_url": "https://github.com/Apollo-R3bot",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/148726450?v=4",
        "html_url": "https://github.com/Apollo-R3bot/django-vulnerability-CVE-2025-32873",
        "description": "Django Security Issue (CVE-2025-32873)",
        "fork": false,
        "created_at": "2025-06-03T09:16:38Z",
        "updated_at": "2025-06-03T09:19:59Z",
        "pushed_at": "2025-06-03T09:34:24Z",
        "stargazers_count": 0,
        "watchers_count": 0,
        "has_discussions": false,
        "forks_count": 0,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": "[]",
        "visibility": "public",
        "forks": 0,
        "watchers": 0,
        "score": 0,
        "subscribers_count": 0
    }
]